### ISSUE TITLE
Bootstrap Radio Buttons Throwing Exception

### ISSUE THREAD

**Issue by Patabugen** [oscarotero/form-manager-bootstrap#4]
There seems to be something amiss with creating radio buttons.

This example from the [FormManager example](https://github.com/oscarotero/form-manager#choose) works fine with regular `\FormManager\Builder` but when using bootstrap throws this exception:

```
Undefined property: FormManager\Containers\Choose::$input
\vendor\form-manager\bootstrap\src\Bootstrap.php:83
```

This is thrown on the `\FormManager\Bootstrap::chosen()` line.

```php
$colors = \FormManager\Bootstrap::choose();

//Add some fields. The keys are the values
$colors->add([
    'red' => \FormManager\Bootstrap::radio()->label('Red'),
    'blue' => \FormManager\Bootstrap::radio()->label('Blue'),
    'green' => \FormManager\Bootstrap::radio()->label('Green')
]);
```

**Comment by oscarotero** [comment]
Hi. This is because this library was created for an older form-manager version. I've fixed this and now it should work fine
Thanks
